# Generated by Django 5.1.1 on 2024-10-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_options_remove_post_created_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("name", models.TextField()),
                ("second_name", models.TextField()),
                ("age", models.IntegerField()),
            ],
        ),
    ]
