# Generated by Django 5.1.1 on 2024-10-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0002_remove_post_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
        migrations.RemoveField(
            model_name="post",
            name="created",
        ),
        migrations.RemoveField(
            model_name="post",
            name="publish",
        ),
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="post",
            name="status",
        ),
        migrations.RemoveField(
            model_name="post",
            name="updated",
        ),
    ]
